/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppManagerRouteImport } from './routes/_app.manager'
import { Route as AppCurriculumRouteImport } from './routes/_app.curriculum'
import { Route as AppCurriculumIndexRouteImport } from './routes/_app.curriculum.index'
import { Route as AppCasesIndexRouteImport } from './routes/_app.cases.index'
import { Route as AppCasesCaseIdRouteImport } from './routes/_app.cases.$caseId'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppManagerRoute = AppManagerRouteImport.update({
  id: '/manager',
  path: '/manager',
  getParentRoute: () => AppRoute,
} as any)
const AppCurriculumRoute = AppCurriculumRouteImport.update({
  id: '/curriculum',
  path: '/curriculum',
  getParentRoute: () => AppRoute,
} as any)
const AppCurriculumIndexRoute = AppCurriculumIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppCurriculumRoute,
} as any)
const AppCasesIndexRoute = AppCasesIndexRouteImport.update({
  id: '/cases/',
  path: '/cases/',
  getParentRoute: () => AppRoute,
} as any)
const AppCasesCaseIdRoute = AppCasesCaseIdRouteImport.update({
  id: '/cases/$caseId',
  path: '/cases/$caseId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/curriculum': typeof AppCurriculumRouteWithChildren
  '/manager': typeof AppManagerRoute
  '/cases/$caseId': typeof AppCasesCaseIdRoute
  '/cases/': typeof AppCasesIndexRoute
  '/curriculum/': typeof AppCurriculumIndexRoute
}
export interface FileRoutesByTo {
  '/manager': typeof AppManagerRoute
  '/': typeof AppIndexRoute
  '/cases/$caseId': typeof AppCasesCaseIdRoute
  '/cases': typeof AppCasesIndexRoute
  '/curriculum': typeof AppCurriculumIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/curriculum': typeof AppCurriculumRouteWithChildren
  '/_app/manager': typeof AppManagerRoute
  '/_app/': typeof AppIndexRoute
  '/_app/cases/$caseId': typeof AppCasesCaseIdRoute
  '/_app/cases/': typeof AppCasesIndexRoute
  '/_app/curriculum/': typeof AppCurriculumIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/curriculum'
    | '/manager'
    | '/cases/$caseId'
    | '/cases/'
    | '/curriculum/'
  fileRoutesByTo: FileRoutesByTo
  to: '/manager' | '/' | '/cases/$caseId' | '/cases' | '/curriculum'
  id:
    | '__root__'
    | '/_app'
    | '/_app/curriculum'
    | '/_app/manager'
    | '/_app/'
    | '/_app/cases/$caseId'
    | '/_app/cases/'
    | '/_app/curriculum/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/manager': {
      id: '/_app/manager'
      path: '/manager'
      fullPath: '/manager'
      preLoaderRoute: typeof AppManagerRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/curriculum': {
      id: '/_app/curriculum'
      path: '/curriculum'
      fullPath: '/curriculum'
      preLoaderRoute: typeof AppCurriculumRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/curriculum/': {
      id: '/_app/curriculum/'
      path: '/'
      fullPath: '/curriculum/'
      preLoaderRoute: typeof AppCurriculumIndexRouteImport
      parentRoute: typeof AppCurriculumRoute
    }
    '/_app/cases/': {
      id: '/_app/cases/'
      path: '/cases'
      fullPath: '/cases/'
      preLoaderRoute: typeof AppCasesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cases/$caseId': {
      id: '/_app/cases/$caseId'
      path: '/cases/$caseId'
      fullPath: '/cases/$caseId'
      preLoaderRoute: typeof AppCasesCaseIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppCurriculumRouteChildren {
  AppCurriculumIndexRoute: typeof AppCurriculumIndexRoute
}

const AppCurriculumRouteChildren: AppCurriculumRouteChildren = {
  AppCurriculumIndexRoute: AppCurriculumIndexRoute,
}

const AppCurriculumRouteWithChildren = AppCurriculumRoute._addFileChildren(
  AppCurriculumRouteChildren,
)

interface AppRouteChildren {
  AppCurriculumRoute: typeof AppCurriculumRouteWithChildren
  AppManagerRoute: typeof AppManagerRoute
  AppIndexRoute: typeof AppIndexRoute
  AppCasesCaseIdRoute: typeof AppCasesCaseIdRoute
  AppCasesIndexRoute: typeof AppCasesIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCurriculumRoute: AppCurriculumRouteWithChildren,
  AppManagerRoute: AppManagerRoute,
  AppIndexRoute: AppIndexRoute,
  AppCasesCaseIdRoute: AppCasesCaseIdRoute,
  AppCasesIndexRoute: AppCasesIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
